id: P003295
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4253
  title: གཞན་སྟོང་དབུ་མ་ཆེན་པོའི་བགྲོ་གླེང་གི་རྩོམ་གཞིའི་དྲིས་ལན་རབ་གསལ་སྣང་བ་
  author: ''
  volumes:
    3978c6715d2d448ebfd40e2f2f9b04eb:
      image_group_id: I1KG4975
      title: ''
      volume_number: 1
      total_pages: 174
