id: P003295
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 10:53:21.802896
source_metadata:
  id: bdr:W1KG4253
  title: གཞན་སྟོང་དབུ་མ་ཆེན་པོའི་བགྲོ་གླེང་གི་རྩོམ་གཞིའི་དྲིས་ལན་རབ་གསལ་སྣང་བ་
  author: ''
  volumes:
    3978c6715d2d448ebfd40e2f2f9b04eb:
      image_group_id: I1KG4975
      title: ''
      volume_number: 1
      total_pages: 174
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
