id: IFE1B000E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:14:28+00:00'
last_modified: '2022-06-07T18:54:37.850245+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4253
  title: གཞན་སྟོང་དབུ་མ་ཆེན་པོའི་བགྲོ་གླེང་གི་རྩོམ་གཞིའི་དྲིས་ལན་རབ་གསལ་སྣང་བ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2B60:
      image_group_id: I1KG4975
      title: ''
      total_pages: 174
      order: 1
      base_file: 2B60.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
