id: IFE1B000E
legacy_id: P003295
ocr_import_info:
  bdrc_scan_id: W1KG4253
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T00:13:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:27:59.968017+00:00'
last_modified: 2022-08-31 23:28:07.569027
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4253
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4253
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཞན་སྟོང་དབུ་མ་ཆེན་པོའི་བགྲོ་གླེང་གི་རྩོམ་གཞིའི་དྲིས་ལན་རབ་གསལ་སྣང་བ།
  author: དངོས་གྲུབ་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.9494900644613088
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG4975:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4975
      total_pages: 174
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4975.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9494900644613088
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
